export const GET_APPOINTMENTS_SUCCESS = "GET_APPOINTMENTS_SUCCESS";
export const GET_APPOINTMENTS_REQUESTED = "GET_APPOINTMENTS_REQUESTED";
export const GET_APPOINTMENTS_ERROR = "GET_APPOINTMENTS_ERROR";

export const SAVE_APPOINTMENT_REQUEST = "SAVE_APPOINTMENT_REQUEST";
export const SAVE_APPOINTMENT_SUCCESS = "SAVE_APPOINTMENT_SUCCESS";
export const SAVE_APPOINTMENT_ERROR = "SAVE_APPOINTMENT_ERROR";

export const SIGNUP_USER_REQUESTED = "SIGNUP_USER_REQUESTED";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";

export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SIGNOUT_USER = "SIGNOUT_USER";

export const SET_API_STATUS_TO_IDLE = "SET_API_STATUS_TO_IDLE";
