export const GET_APPOINTMENTS_SUCCESS = "GET_APPOINTMENTS_SUCCESS";
export const GET_APPOINTMENTS_REQUESTED = "GET_APPOINTMENTS_REQUESTED";
export const GET_APPOINTMENTS_ERROR = "GET_APPOINTMENTS_ERROR";

export const SAVE_APPOINTMENT_REQUEST = "SAVE_APPOINTMENT_REQUEST";
export const SAVE_APPOINTMENT_SUCCESS = "SAVE_APPOINTMENT_SUCCESS";
export const SAVE_APPOINTMENT_ERROR = "SAVE_APPOINTMENT_ERROR";

export const SET_API_STATUS_TO_IDLE = "SET_API_STATUS_TO_IDLE";
